<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_11_ColumnTransformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [8]:
X_train

    age  gender  fever   cough       city
5    84  Female    NaN    Mild  Bangalore
12   25  Female   99.0  Strong    Kolkata
82   24    Male   98.0    Mild    Kolkata
72   83  Female  101.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
..  ...     ...    ...     ...        ...
21   73    Male   98.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
27   33  Female  102.0  Strong      Delhi
13   64    Male  102.0    Mild  Bangalore
42   27    Male  100.0    Mild      Delhi

[80 rows x 5 columns]

In [9]:
#  adding simple imputer  to fever column

si=SimpleImputer(strategy="mean")
X_train_fever=si.fit_transform(X_train[["fever"]])

#  also the test data
X_test_fever=si.fit_transform(X_test[["fever"]])

X_train_fever.shape

(80, 1)

In [10]:
#  ordinal encoding ----> cough

oe=OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough=oe.fit_transform(X_train[["cough"]])

#  also the test data
X_test_cough=oe.fit_transform(X_test[["cough"]])

X_train_cough.shape

(80, 1)

In [11]:
# one hote encoder ---> gender ,city

ohe=OneHotEncoder(drop="first",sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[["gender","city"]])


#  also the test data
X_test_gender_city=ohe.fit_transform(X_test[["gender","city"]])

X_train_gender_city.shape

(80, 4)

In [12]:
# Extracting age

X_train_age=X_train.drop(columns=["gender","fever","cough","city"]).values

#  also the test data
X_test_age=X_test.drop(columns=["gender","fever","cough","city"]).values

X_train_age.shape

(80, 1)

In [13]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

 by the help of Column Transformer

In [14]:
from sklearn.compose import ColumnTransformer    # this is how to import column transformer

transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),         # in a 'fever' column by the help of SI we fill missing values by mean. median , mode
    ("tnf2",OrdinalEncoder(categories=[['Mild','Strong']]),["cough"]),   # by this process we encode our data
    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["gender","city"])    ##
],remainder="passthrough")    # remainder ===> passthrough ==> it means rest all the column remain same.

In [15]:
transformer.fit_transform(X_train).shape

(80, 7)

In [16]:
# ## new data  insaurance

In [17]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [18]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [19]:
#  remove duplicate
# df.drop_duplicates(inplace=True)

In [20]:
 from sklearn.model_selection import train_test_split

 X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=["charges"]),df["charges"],test_size=0.2)

In [21]:
X_train

      age     sex     bmi  children smoker     region
759    18    male  38.170         0    yes  southeast
877    33    male  33.440         5     no  southeast
648    18    male  28.500         0     no  northeast
3      33    male  22.705         0     no  northwest
1029   37  female  17.290         2     no  northeast
...   ...     ...     ...       ...    ...        ...
1214   27  female  31.255         1     no  northwest
84     37  female  34.800         2    yes  southwest
386    58  female  39.050         0     no  southeast
27     55  female  32.775         2     no  northwest
967    44    male  25.365         1     no  northwest

[1070 rows x 6 columns]

In [22]:
#  adding a simple imput to bmi column

si=SimpleImputer(strategy="mean")
X_train_bmi=si.fit_transform(X_train[["bmi"]])


X_train_bmi.shape

(1070, 1)

In [23]:
#  column transformer
from sklearn.compose import ColumnTransformer

transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["bmi"]),         # in a 'fever' column by the help of SI we fill missing values by mean. median , mode
    ("tnf2",OrdinalEncoder(categories=[['yes','no']]),["smoker"]),   # by this process we encode our data
    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["sex","region"])    ##
],remainder="passthrough")    # remainder ===> passthrough ==> it means rest all the column remain same.


transformer.fit_transform(X_train).shape

(1070, 8)

In [32]:
### New Data ===> Tips

df=pd.read_csv("/content/tips - tips.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [43]:
df.shape

(243, 7)

In [34]:
df.drop(columns='day')

     total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

In [35]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [36]:
#  check duplicate
df.duplicated().sum()

np.int64(1)

In [37]:
df.drop_duplicates(inplace=True)

In [38]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["tip"]),df["tip"],test_size=0.2)

In [39]:
x_train

     total_bill     sex smoker   day    time  size
20        17.92    Male     No   Sat  Dinner     2
65        20.08    Male     No   Sat  Dinner     3
135        8.51  Female     No  Thur   Lunch     2
242       17.82    Male     No   Sat  Dinner     2
229       22.12  Female    Yes   Sat  Dinner     2
..          ...     ...    ...   ...     ...   ...
84        15.98    Male     No  Thur   Lunch     2
61        13.81    Male    Yes   Sat  Dinner     2
166       20.76    Male     No   Sun  Dinner     2
29        19.65  Female     No   Sat  Dinner     2
117       10.65  Female     No  Thur   Lunch     2

[194 rows x 6 columns]

In [42]:
#  column transfer

from sklearn.compose import ColumnTransformer

transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["total_bill"]),
    ("tnf2",OrdinalEncoder(categories=[['Yes','No']]),["smoker"]),
    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["sex","time"])
],remainder="passthrough")

transformer.fit_transform(x_train).shape

(194, 6)