<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_3_practiceStandardScaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02-04-2026

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df=df.drop(columns=['day','time'])
df

     total_bill   tip     sex smoker  size
0         16.99  1.01  Female     No     2
1         10.34  1.66    Male     No     3
2         21.01  3.50    Male     No     3
3         23.68  3.31    Male     No     2
4         24.59  3.61  Female     No     4
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No     3
240       27.18  2.00  Female    Yes     2
241       22.67  2.00    Male    Yes     2
242       17.82  1.75    Male     No     2
243       18.78  3.00  Female     No     2

[244 rows x 5 columns]

In [ ]:
df['sex']=df['sex'].map({'Female':0,'Male':1})
df['smoker']=df['smoker'].map({'No':0,'Yes':1})
df

     total_bill   tip  sex  smoker  size
0         16.99  1.01    0       0     2
1         10.34  1.66    1       0     3
2         21.01  3.50    1       0     3
3         23.68  3.31    1       0     2
4         24.59  3.61    0       0     4
..          ...   ...  ...     ...   ...
239       29.03  5.92    1       0     3
240       27.18  2.00    0       1     2
241       22.67  2.00    1       1     2
242       17.82  1.75    1       0     2
243       18.78  3.00    0       0     2

[244 rows x 5 columns]

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'size'], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc

StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)
x_train_sc

array([[-2.58032900e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.42114421e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 6.39973400e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 9.90757111e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-7.42114421e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.96205363e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.44677594e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-9.38553299e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-2.44001552e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [ 1.43976026e+00, -1.36661884e+00, -7.90569415e-01,
         2.58520127e+00],
       [ 2.89189689e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.79755965e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-4.12377733e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-7.56145770e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 6.96098794e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-7.00020376e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.46472887e+00, -1.36661884e+00, -7.90569415e-01,
        -1.67792133e+00],
       [ 2.26048621e-01,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [ 2.75158341e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
         2.58520127e+00],
       [-2.65048574e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 4.15471825e-01,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 1.13808627e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 7.80286885e-01, -1.36661884e+00, -7.90569415e-01,
         3.65098192e+00],
       [-9.52584648e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 6.39973400e-01, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [ 4.36410914e-02,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-1.11394516e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [-7.63161444e-01, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [-4.12377733e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-1.06483544e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 3.59346431e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 8.50443627e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-1.94999766e-02,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.98698285e+00,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-1.12797650e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 8.50443627e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-3.42220991e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.15211762e+00,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 2.89189689e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 6.39973400e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-5.46862811e-03,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-3.84315036e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 4.71597219e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-5.52691217e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-1.28933701e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-4.12377733e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 2.39389196e+00,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [-7.49130096e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.45771319e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.89189689e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 6.39973400e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 1.34154082e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-4.12377733e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-1.02274139e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.55783946e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 1.46080728e+00, -1.36661884e+00, -7.90569415e-01,
         1.51942062e+00],
       [ 4.84937793e+00,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [-4.12377733e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 1.34154082e+00, -1.36661884e+00, -7.90569415e-01,
         3.65098192e+00],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-6.01800937e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-9.03474928e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-3.35205316e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.34154082e+00, -1.36661884e+00, -7.90569415e-01,
         1.51942062e+00],
       [ 1.11002357e+00, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-4.12377733e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 3.66362106e-01, -1.36661884e+00, -7.90569415e-01,
         1.51942062e+00],
       [-4.12377733e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.53420544e+00,  7.31732923e-01, -7.90569415e-01,
         3.65098192e+00],
       [ 6.46881141e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.77192792e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.28933701e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-6.22847960e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.84208467e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 9.97664852e-02, -1.36661884e+00,  1.26491106e+00,
         4.53639970e-01],
       [-3.14158294e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 1.76248128e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 1.54704611e-03, -1.36661884e+00,  1.26491106e+00,
         1.51942062e+00],
       [-5.94785263e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 3.15158477e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 2.89189689e-01,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [ 6.39973400e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 2.19032947e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.34154082e+00,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 6.39973400e-01,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 2.04310824e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 1.13797834e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.34154082e+00,  7.31732923e-01, -7.90569415e-01,
         2.58520127e+00],
       [-1.24022729e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-1.11394516e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-1.11394516e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 1.55891879e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-1.01572572e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.07185111e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.75158341e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-1.34546240e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 1.27829182e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.56145770e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 2.25940688e-02,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 5.06567657e-02,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.89189689e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.34154082e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.11394516e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-8.19286838e-01,  7.31732923e-01,  1.26491106e+00,
        -1.67792133e+00],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.91224141e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 2.55525246e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-6.01800937e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-1.80860484e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 4.36518848e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-5.94785263e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 3.66254172e-02, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 2.12017273e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.13797834e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-1.05781976e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 4.71597219e-01,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 8.78506324e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 8.43427953e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-4.12377733e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
         1.51942062e+00],
       [ 6.39973400e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [ 4.14781051e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 6.39973400e-01,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [-7.63161444e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-1.39457212e+00, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-9.31537625e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.28083073e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 1.93787313e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-2.36985877e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-1.11394516e+00, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-4.12377733e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 2.89189689e-01,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [-1.46472887e+00,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
         2.58520127e+00],
       [ 7.73271210e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-6.36879308e-01,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [-1.24843023e-02, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [ 4.64581545e-01, -1.36661884e+00, -7.90569415e-01,
         1.51942062e+00],
       [-1.45782113e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-1.00169437e+00,  7.31732923e-01, -7.90569415e-01,
         4.53639970e-01],
       [ 1.48185431e+00, -1.36661884e+00, -7.90569415e-01,
         1.51942062e+00],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-1.11394516e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.75158341e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-1.11394516e+00,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 1.39065054e+00,  7.31732923e-01, -7.90569415e-01,
         1.51942062e+00],
       [ 6.39973400e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [-7.63161444e-01, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [-6.22847960e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.39389196e+00, -1.36661884e+00,  1.26491106e+00,
         4.53639970e-01],
       [-7.63161444e-01,  7.31732923e-01,  1.26491106e+00,
         4.53639970e-01],
       [-9.87663019e-01, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-6.15940219e-02, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [ 6.96098794e-01,  7.31732923e-01, -7.90569415e-01,
        -6.12140682e-01],
       [ 2.89189689e-01, -1.36661884e+00,  1.26491106e+00,
         4.53639970e-01],
       [-6.15940219e-02, -1.36661884e+00, -7.90569415e-01,
         4.53639970e-01],
       [ 6.82067446e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-4.75626734e-02, -1.36661884e+00, -7.90569415e-01,
        -6.12140682e-01],
       [-1.46472887e+00, -1.36661884e+00,  1.26491106e+00,
        -6.12140682e-01],
       [ 3.24268060e-01,  7.31732923e-01,  1.26491106e+00,
        -6.12140682e-01],
       [-4.12377733e-01, -1.36661884e+00,  1.26491106e+00,
         4.53639970e-01]])

In [ ]:
x_train_sc_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_sc_new

          tip       sex    smoker      size
0   -0.258033  0.731733 -0.790569 -0.612141
1   -0.742114  0.731733  1.264911 -0.612141
2    0.639973  0.731733  1.264911 -0.612141
3    0.990757  0.731733 -0.790569  1.519421
4   -0.742114  0.731733 -0.790569 -0.612141
..        ...       ...       ...       ...
190  0.682067  0.731733  1.264911 -0.612141
191 -0.047563 -1.366619 -0.790569 -0.612141
192 -1.464729 -1.366619  1.264911 -0.612141
193  0.324268  0.731733  1.264911 -0.612141
194 -0.412378 -1.366619  1.264911  0.453640

[195 rows x 4 columns]

In [ ]:
np.round(x_train_sc_new.describe(),2)

          tip     sex  smoker    size
count  195.00  195.00  195.00  195.00
mean    -0.00   -0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00
min     -1.46   -1.37   -0.79   -1.68
25%     -0.76   -1.37   -0.79   -0.61
50%     -0.06    0.73   -0.79   -0.61
75%      0.43    0.73    1.26    0.45
max      4.85    0.73    1.26    3.65