<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_5_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Encodeing -->>> Transfro your categorical data into numerical data

In [ ]:
# (1). LabelEncode ---->> has_covid['yes','no']-->> value_counts() -->>encode --->has_covid(1,0)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df=df.dropna()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
df['gender']=lb.fit_transform(df['gender'])

In [ ]:
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [ ]:
df.head(3)

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
# Apply standardization for converting my data into normal distribution

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
sc

StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)
x_train_sc

array([[ 0.2178123 , -0.75180941, -0.82611344,  1.37113092, -1.20482899],
       [ 0.97407431, -0.75180941,  0.12556924,  1.37113092, -0.2409658 ],
       [ 0.85466452,  1.33012434, -0.82611344, -0.72932496, -0.2409658 ],
       [-1.4141215 , -0.75180941,  0.12556924, -0.72932496,  0.7228974 ],
       [ 1.01387757, -0.75180941, -1.30195479,  1.37113092,  1.68676059],
       [-0.2200236 , -0.75180941,  0.12556924, -0.72932496, -1.20482899],
       [ 0.25761557, -0.75180941,  1.07725193, -0.72932496,  0.7228974 ],
       [ 0.29741883,  1.33012434,  1.55309327, -0.72932496, -1.20482899],
       [-0.37923665, -0.75180941,  1.55309327,  1.37113092, -0.2409658 ],
       [-1.53353129,  1.33012434,  0.60141059, -0.72932496,  0.7228974 ],
       [ 0.45663188,  1.33012434, -0.3502721 , -0.72932496,  0.7228974 ],
       [-1.05589213, -0.75180941,  1.55309327, -0.72932496,  0.7228974 ],
       [-0.73746602, -0.75180941, -0.82611344,  1.37113092,  0.7228974 ],
       [ 1.45171347,  1.33012434, -0.3502721 , -0.72932496, -1.20482899],
       [-1.17530192,  1.33012434,  0.12556924,  1.37113092, -1.20482899],
       [ 0.01879599,  1.33012434,  1.55309327, -0.72932496,  1.68676059],
       [ 0.6556482 , -0.75180941, -0.82611344, -0.72932496,  1.68676059],
       [-1.25490845,  1.33012434, -1.30195479,  1.37113092, -1.20482899],
       [ 0.13820578, -0.75180941, -0.3502721 ,  1.37113092, -1.20482899],
       [ 0.2178123 , -0.75180941,  0.60141059, -0.72932496, -0.2409658 ],
       [ 0.81486126, -0.75180941,  0.12556924, -0.72932496, -0.2409658 ],
       [-0.73746602,  1.33012434,  1.55309327, -0.72932496, -1.20482899],
       [-0.69766276, -0.75180941, -1.30195479, -0.72932496,  0.7228974 ],
       [ 1.45171347, -0.75180941, -1.30195479, -0.72932496, -0.2409658 ],
       [-0.65785949,  1.33012434, -0.3502721 , -0.72932496,  0.7228974 ],
       [ 1.57112326,  1.33012434,  1.07725193, -0.72932496,  0.7228974 ],
       [ 1.49151673, -0.75180941, -1.30195479,  1.37113092,  1.68676059],
       [ 1.01387757, -0.75180941,  1.07725193, -0.72932496,  0.7228974 ],
       [-1.13549866,  1.33012434,  0.12556924, -0.72932496, -0.2409658 ],
       [-0.49864644, -0.75180941, -1.30195479, -0.72932496,  0.7228974 ],
       [ 1.17309063,  1.33012434, -1.30195479, -0.72932496, -1.20482899],
       [ 1.13328736,  1.33012434, -0.82611344, -0.72932496, -1.20482899],
       [ 0.85466452, -0.75180941, -1.30195479, -0.72932496,  1.68676059],
       [-0.93648234, -0.75180941,  0.12556924, -0.72932496, -1.20482899],
       [-0.9762856 , -0.75180941, -0.3502721 ,  1.37113092, -1.20482899],
       [ 1.57112326, -0.75180941,  0.12556924, -0.72932496,  0.7228974 ],
       [-0.85687581, -0.75180941, -0.82611344, -0.72932496, -1.20482899],
       [-1.53353129, -0.75180941, -0.3502721 , -0.72932496,  0.7228974 ],
       [-1.33451497, -0.75180941, -1.30195479,  1.37113092,  0.7228974 ],
       [ 0.49643515, -0.75180941,  1.55309327,  1.37113092, -1.20482899],
       [-0.9762856 ,  1.33012434,  0.12556924, -0.72932496, -0.2409658 ],
       [-0.81707255,  1.33012434, -1.30195479,  1.37113092,  1.68676059],
       [ 1.57112326,  1.33012434, -1.30195479, -0.72932496, -0.2409658 ],
       [ 1.17309063, -0.75180941,  1.07725193, -0.72932496, -0.2409658 ],
       [-1.53353129, -0.75180941, -1.30195479,  1.37113092,  1.68676059],
       [ 0.81486126, -0.75180941, -1.30195479, -0.72932496, -1.20482899],
       [-1.17530192, -0.75180941, -0.82611344, -0.72932496,  1.68676059],
       [ 0.89446778,  1.33012434, -0.82611344,  1.37113092, -1.20482899],
       [ 0.29741883,  1.33012434,  1.55309327, -0.72932496,  0.7228974 ],
       [ 1.49151673, -0.75180941,  0.12556924, -0.72932496,  1.68676059],
       [ 0.13820578,  1.33012434,  0.12556924,  1.37113092, -1.20482899],
       [ 1.01387757, -0.75180941,  0.60141059, -0.72932496, -1.20482899],
       [ 0.2178123 , -0.75180941,  0.12556924, -0.72932496, -0.2409658 ],
       [-1.25490845, -0.75180941,  1.55309327, -0.72932496, -1.20482899],
       [ 0.85466452,  1.33012434, -0.82611344, -0.72932496, -1.20482899],
       [ 1.25269715, -0.75180941,  1.55309327,  1.37113092, -0.2409658 ],
       [-1.09569539, -0.75180941,  1.07725193, -0.72932496, -1.20482899],
       [-0.93648234,  1.33012434,  0.60141059,  1.37113092, -0.2409658 ],
       [ 1.53132   , -0.75180941,  0.60141059,  1.37113092, -1.20482899],
       [-0.65785949,  1.33012434, -0.3502721 , -0.72932496, -0.2409658 ],
       [-0.77726928, -0.75180941,  0.60141059,  1.37113092, -1.20482899],
       [-0.9762856 , -0.75180941, -0.3502721 , -0.72932496,  0.7228974 ],
       [-0.06081054,  1.33012434,  0.12556924, -0.72932496, -0.2409658 ],
       [-1.09569539,  1.33012434,  1.55309327, -0.72932496,  0.7228974 ],
       [ 1.53132   , -0.75180941,  0.60141059,  1.37113092,  0.7228974 ],
       [-0.77726928,  1.33012434, -1.30195479, -0.72932496,  0.7228974 ],
       [ 0.61584494, -0.75180941, -0.82611344,  1.37113092, -0.2409658 ],
       [-1.21510518, -0.75180941, -0.3502721 ,  1.37113092,  0.7228974 ],
       [ 0.41682862, -0.75180941,  1.55309327,  1.37113092,  0.7228974 ],
       [ 0.17800904, -0.75180941,  1.07725193, -0.72932496,  0.7228974 ],
       [-0.14041707, -0.75180941, -1.30195479,  1.37113092, -0.2409658 ],
       [-1.49372803, -0.75180941,  1.55309327, -0.72932496,  0.7228974 ]])

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_new

         age    gender     fever     cough      city
0   0.217812 -0.751809 -0.826113  1.371131 -1.204829
1   0.974074 -0.751809  0.125569  1.371131 -0.240966
2   0.854665  1.330124 -0.826113 -0.729325 -0.240966
3  -1.414122 -0.751809  0.125569 -0.729325  0.722897
4   1.013878 -0.751809 -1.301955  1.371131  1.686761
..       ...       ...       ...       ...       ...
67 -1.215105 -0.751809 -0.350272  1.371131  0.722897
68  0.416829 -0.751809  1.553093  1.371131  0.722897
69  0.178009 -0.751809  1.077252 -0.729325  0.722897
70 -0.140417 -0.751809 -1.301955  1.371131 -0.240966
71 -1.493728 -0.751809  1.553093 -0.729325  0.722897

[72 rows x 5 columns]

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean   -0.00   -0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.53   -0.75  -1.30  -0.73  -1.20
25%    -0.95   -0.75  -0.83  -0.73  -1.20
50%     0.14   -0.75   0.13  -0.73  -0.24
75%     0.86    1.33   0.72   1.37   0.72
max     1.57    1.33   1.55   1.37   1.69

In [ ]:
### NEW data

df=pd.read_csv("/content/tips - tips.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df=df.dropna()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()
lb

LabelEncoder()

In [ ]:
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])
df['smoker']=lb.fit_transform(df['smoker'])
df['sex']=lb.fit_transform(df['sex'])
df.head(2)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
# Apply normalization

from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn=MinMaxScaler()
mn

MinMaxScaler()

In [ ]:
x_train_mn=mn.fit_transform(x_train)
x_train_mn

array([[0.19111111, 1.        , 0.        , 0.33333333, 0.        ,
        0.2       ],
       [0.11444444, 1.        , 1.        , 0.33333333, 0.        ,
        0.2       ],
       [0.33333333, 1.        , 1.        , 0.        , 0.        ,
        0.2       ],
       ...,
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.2       ],
       [0.28333333, 1.        , 1.        , 0.66666667, 0.        ,
        0.2       ],
       [0.16666667, 0.        , 1.        , 0.33333333, 0.        ,
        0.4       ]])

In [ ]:
x_train_new=pd.DataFrame(x_train_mn,columns=x_train.columns)
x_train_new

          tip  sex  smoker       day  time  size
0    0.191111  1.0     0.0  0.333333   0.0   0.2
1    0.114444  1.0     1.0  0.333333   0.0   0.2
2    0.333333  1.0     1.0  0.000000   0.0   0.2
3    0.388889  1.0     0.0  0.666667   0.0   0.6
4    0.114444  1.0     0.0  1.000000   1.0   0.2
..        ...  ...     ...       ...   ...   ...
190  0.340000  1.0     1.0  0.333333   0.0   0.2
191  0.224444  0.0     0.0  0.666667   0.0   0.2
192  0.000000  0.0     1.0  0.000000   0.0   0.2
193  0.283333  1.0     1.0  0.666667   0.0   0.2
194  0.166667  0.0     1.0  0.333333   0.0   0.4

[195 rows x 6 columns]

In [ ]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.65    0.38    0.57    0.27    0.31
std      0.16    0.48    0.49    0.31    0.45    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.30    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00

In [ ]:
# ### NEW data
#  insurance data ---> LabelEncoder ----> StandardScaler

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df=df.dropna()

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])
df.head(2)

   age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [ ]:
# labelEncoder

from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']
x.head(2)

   age  sex    bmi  children  smoker  region
0   19    0  27.90         0       1       3
1   18    1  33.77         1       0       2

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
sc

StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)
x_train_sc

array([[ 0.47222651, -1.0246016 , -1.75652513,  0.73433626, -0.50874702,
        -0.45611589],
       [ 0.54331294, -1.0246016 , -1.03308239, -0.91119211, -0.50874702,
        -1.35325561],
       [ 0.8987451 , -1.0246016 , -0.94368672, -0.91119211, -0.50874702,
         0.44102382],
       ...,
       [ 1.3252637 ,  0.97598911, -0.89153925, -0.91119211, -0.50874702,
        -1.35325561],
       [-0.16755139, -1.0246016 ,  2.82086429,  0.73433626,  1.96561348,
         1.33816354],
       [ 1.1120044 ,  0.97598911, -0.10932713, -0.91119211, -0.50874702,
         1.33816354]])

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_new

           age       sex       bmi  children    smoker    region
0     0.472227 -1.024602 -1.756525  0.734336 -0.508747 -0.456116
1     0.543313 -1.024602 -1.033082 -0.911192 -0.508747 -1.353256
2     0.898745 -1.024602 -0.943687 -0.911192 -0.508747  0.441024
3    -0.025379 -1.024602  0.622393  3.202629 -0.508747  0.441024
4     1.040918 -1.024602 -1.504893  1.557100 -0.508747 -0.456116
...        ...       ...       ...       ...       ...       ...
1065 -1.518194 -1.024602  0.130717  2.379865 -0.508747 -1.353256
1066 -0.025379 -1.024602 -1.107579  3.202629 -0.508747  0.441024
1067  1.325264  0.975989 -0.891539 -0.911192 -0.508747 -1.353256
1068 -0.167551 -1.024602  2.820864  0.734336  1.965613  1.338164
1069  1.112004  0.975989 -0.109327 -0.911192 -0.508747  1.338164

[1070 rows x 6 columns]

In [ ]:
np.round(x_train_new.describe(),2)

           age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean     -0.00    -0.00    -0.00     -0.00     0.00    -0.00
std       1.00     1.00     1.00      1.00     1.00     1.00
min      -1.52    -1.02    -2.42     -0.91    -0.51    -1.35
25%      -0.88    -1.02    -0.72     -0.91    -0.51    -0.46
50%       0.01     0.98    -0.06     -0.09    -0.51     0.44
75%       0.83     0.98     0.65      0.73    -0.51     0.44
max       1.75     0.98     3.74      3.20     1.97     1.34