<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_6_OridnalEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Ordinal Encoding --->
# Label Encoding ---> column[sub1,syub2,sub3...subn] ---> encode
# Ordinal Encoding ---> column[sub1,sub2,...subn] ---> Re-Arrange ---> encode

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns = ['city', 'age', 'fever'])

In [ ]:
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['No','Yes']])

In [ ]:
oe_ar = oe.fit_transform(df)

In [ ]:
new_df = pd.DataFrame(oe_ar, columns = df.columns)

In [ ]:
# new_df

In [ ]:
# Second Way :::::

In [ ]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
# df.head(2)

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns = ['age','fever','city'])

In [ ]:
df.head(3)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes
2   Male  Mild        No

In [ ]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [ ]:
x.head(2)

  gender cough
0   Male  Mild
1   Male  Mild

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong']])

In [ ]:
oe_ar_in = oe.fit_transform(x)

In [ ]:
y.head(2)

0     No
1    Yes
Name: has_covid, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
y = lb.fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1])

In [ ]:
# LabelEncoder ---> when we have single column . we cannot set sub-category form .
# has_covid['yes','no'] ---> labelecoder --> [1,0]
# OrdinalEncoder ---> when we have multiple columns .we can set sub-category form.
# has_covid['yes','no'] ---> ord. encoder ---> [0,1]

In [ ]:
# first approach ::::
# df ---> categorical column ---> ordinal encoder ---> data transform
# second approach ::::
# df ---> x,y --->
# x ---> encode by Ordinal Encoder
# y ---> encode by Label Encoder

In [ ]:
# tips data --->
# target column 'total_bill'
# Numerical columns ---> remove
# Categorical column ---> OrdinalEncoder

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['total_bill','tip','size','day'])
df.head(2)

      sex smoker    time
0  Female     No  Dinner
1    Male     No  Dinner

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Yes','No'],['Dinner','Lunch']])

In [ ]:
oe_ar=oe.fit_transform(df)

In [ ]:
new_df=pd.DataFrame(oe_ar,columns=df.columns)
new_df

     sex  smoker  time
0    1.0     1.0   0.0
1    0.0     1.0   0.0
2    0.0     1.0   0.0
3    0.0     1.0   0.0
4    1.0     1.0   0.0
..   ...     ...   ...
239  0.0     1.0   0.0
240  1.0     0.0   0.0
241  0.0     0.0   0.0
242  0.0     1.0   0.0
243  1.0     1.0   0.0

[244 rows x 3 columns]