<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_7_get_dummies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  Encoding : -->> get_dummies

# column --->has_covid ['Yes' , 'No'] --->> when we apply get_dummies-->> create two columns -->> has_covid_yes , has_covid_no

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/insurance - insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df=df.dropna()

In [ ]:
a=pd.get_dummies(df,columns=['sex','smoker','region',])
a.head(2)

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,True,False,False,True,False,False,False,True
1,18,33.77,1,1725.5523,False,True,True,False,False,False,True,False

In [ ]:
a=a.astype(int)

In [ ]:
# a

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,1,0,0,1,0,0,0,1
1,18,33,1,1725,0,1,1,0,0,0,1,0
2,28,33,3,4449,0,1,1,0,0,0,1,0
3,33,22,0,21984,0,1,1,0,0,1,0,0
4,32,28,0,3866,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,0,1,1,0,0,1,0,0
1334,18,31,0,2205,1,0,1,0,1,0,0,0
1335,18,36,0,1629,1,0,1,0,0,0,1,0
1336,21,25,0,2007,1,0,1,0,0,0,0,1
1337,61,29,0,29141,1,0,0,1,0,1,0,0

In [ ]:
#  if i have multiple sub-categories ---> 1 column drop --->> Data multiconielity
#  issue resolve
#  model  ---->> overfitting --->
#  1 student --> 2 days exam --> exam paper ---> exam clear
#  but 3 days --->>> question answer --->> xxx

In [ ]:
b=pd.get_dummies(df,columns=['sex','smoker','region',],drop_first=True)
b.head(2)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,False,True,False,False,True
1,18,33.77,1,1725.5523,True,False,False,True,False

In [ ]:
b=b.astype(int)

In [ ]:
b

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,0,1,0,0,1
1,18,33,1,1725,1,0,0,1,0
2,28,33,3,4449,1,0,0,1,0
3,33,22,0,21984,1,0,1,0,0
4,32,28,0,3866,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,1,0,1,0,0
1334,18,31,0,2205,0,0,0,0,0
1335,18,36,0,1629,0,0,0,1,0
1336,21,25,0,2007,0,0,0,0,1
1337,61,29,0,29141,0,1,1,0,0

In [ ]:
#  covid -->
#  entire categorical data
#  1-1 sub category drop

# encode

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
# df.isnull().sum()
# df=df.dropna()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
a=pd.get_dummies(df,columns=['cough','gender','city','has_covid'])
a.head(2)

,age,fever,cough_Mild,cough_Strong,gender_Female,gender_Male,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai,has_covid_No,has_covid_Yes
0,60,103.0,True,False,False,True,False,False,True,False,True,False
1,27,100.0,True,False,False,True,False,True,False,False,False,True

In [ ]:
a=a.astype(int)
a

,age,fever,cough_Mild,cough_Strong,gender_Female,gender_Male,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai,has_covid_No,has_covid_Yes
0,60,103,1,0,0,1,0,0,1,0,1,0
1,27,100,1,0,0,1,0,1,0,0,0,1
2,42,101,1,0,0,1,0,1,0,0,1,0
3,31,98,1,0,1,0,0,0,1,0,1,0
4,65,101,1,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104,1,0,1,0,1,0,0,0,1,0
96,51,101,0,1,1,0,0,0,1,0,0,1
97,20,101,1,0,1,0,1,0,0,0,1,0
98,5,98,0,1,1,0,0,0,0,1,1,0
99,10,98,0,1,1,0,0,0,1,0,0,1

In [ ]:
# ## sub

b=pd.get_dummies(df,columns=['cough','gender','city','has_covid'],drop_first=True)
b.head(2)

,age,fever,cough_Strong,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,60,103.0,False,True,False,True,False,False
1,27,100.0,False,True,True,False,False,True

In [ ]:
b=b.astype(int)
b.head(2)

,age,fever,cough_Strong,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,has_covid_Yes
0,60,103,0,1,0,1,0,0
1,27,100,0,1,1,0,0,1

In [ ]:
### Tips data --->>

df=pd.read_csv("/content/tips - tips.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df=df.drop(columns=['day'])

In [ ]:
df.head(2)

   total_bill   tip     sex smoker    time  size
0       16.99  1.01  Female     No  Dinner     2
1       10.34  1.66    Male     No  Dinner     3

In [ ]:
a=pd.get_dummies(df,columns=['sex','smoker','time'])
a.head(2)

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,time_Dinner,time_Lunch
0,16.99,1.01,2,True,False,True,False,True,False
1,10.34,1.66,3,False,True,True,False,True,False

In [ ]:
a=a.astype(int)
a.head(2)

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,time_Dinner,time_Lunch
0,16,1,2,1,0,1,0,1,0
1,10,1,3,0,1,1,0,1,0

In [ ]:
### sub

b=pd.get_dummies(df,columns=['sex','smoker','time'],drop_first=True)
b.head(2)

   total_bill   tip  size  sex_Male  smoker_Yes  time_Lunch
0       16.99  1.01     2     False       False       False
1       10.34  1.66     3      True       False       False

In [ ]:
b=b.astype(int)
b.head(2)

   total_bill  tip  size  sex_Male  smoker_Yes  time_Lunch
0          16    1     2         0           0           0
1          10    1     3         1           0           0

Encoding -4

In [ ]:
#  OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [ ]:
ohe.fit_transform(df[['sex','smoker','time']])

array([[0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]], dtype=int32)