<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_9_Coffee_sales_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Coffe_sales - Coffe_sales.csv')
df.head(2)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:51
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:23

In [ ]:
df.drop(columns=['Date','Time','Month_name','Weekday'], inplace=True)

df.head(2)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekdaysort,Monthsort
0,10,card,38.7,Latte,Morning,5,3
1,12,card,38.7,Hot Chocolate,Afternoon,5,3

In [ ]:
df.isnull().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekdaysort    0
Monthsort      0
dtype: int64

In [ ]:
X = df.drop('money', axis=1)
y = df['money']

X.head()
# y.head()

   hour_of_day cash_type    coffee_name Time_of_Day  Weekdaysort  Monthsort
0           10      card          Latte     Morning            5          3
1           12      card  Hot Chocolate   Afternoon            5          3
2           12      card  Hot Chocolate   Afternoon            5          3
3           13      card      Americano   Afternoon            5          3
4           13      card          Latte   Afternoon            5          3

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X['cash_type'] = le.fit_transform(X['cash_type'])

X.head()

   hour_of_day  cash_type    coffee_name Time_of_Day  Weekdaysort  Monthsort
0           10          0          Latte     Morning            5          3
1           12          0  Hot Chocolate   Afternoon            5          3
2           12          0  Hot Chocolate   Afternoon            5          3
3           13          0      Americano   Afternoon            5          3
4           13          0          Latte   Afternoon            5          3

In [ ]:

X = pd.get_dummies(X, columns=['coffee_name','Time_of_Day'], drop_first=True)

X.head(2)

,hour_of_day,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
0,10,0,5,3,False,False,False,False,False,False,True,True,False
1,12,0,5,3,False,False,False,False,False,True,False,False,False

In [ ]:
X=X.astype(int)
X.head(2)

,hour_of_day,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
0,10,0,5,3,0,0,0,0,0,0,1,1,0
1,12,0,5,3,0,0,0,0,0,1,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (2837, 13)
Test shape: (710, 13)

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

num_cols=['hour_of_day','Weekdaysort','Monthsort']

X_train[num_cols] = sc.fit_transform(X_train[num_cols])
X_test[num_cols] = sc.transform(X_test[num_cols])

X_train.head(2)

,hour_of_day,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
1149,1.616003,0,1.613669,0.442535,0,0,0,1,0,0,0,0,1
195,-0.037382,0,0.595322,-0.699062,0,0,0,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()

num_cols = ['hour_of_day', 'Weekdaysort', 'Monthsort']

X_train[num_cols] = mm.fit_transform(X_train[num_cols])
X_test[num_cols] = mm.transform(X_test[num_cols])

X_train.head()

,hour_of_day,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
1149,0.9375,0,1.000000,0.636364,0,0,0,1,0,0,0,0,1
195,0.5000,0,0.666667,0.272727,0,0,0,0,0,0,1,0,0
532,0.5625,0,0.000000,0.363636,0,0,0,0,0,0,0,0,0
2486,0.4375,0,0.500000,1.000000,0,0,0,0,0,1,0,0,0
2166,0.2500,0,0.833333,0.909091,1,0,0,0,0,0,0,1,0

In [ ]:
#  filter index 30 to 40

X_train_norm_df.iloc[30:41]

,hour,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
30,0.6875,0.0,0.333333,0.818182,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
31,0.1250,0.0,0.833333,0.090909,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
32,0.6875,0.0,0.833333,0.545455,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
33,0.3125,0.0,0.833333,0.181818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34,0.8750,0.0,0.166667,0.454545,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
35,0.3750,0.0,0.166667,0.727273,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
36,0.3750,0.0,0.000000,0.181818,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,0.3750,0.0,1.000000,0.727273,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
38,0.2500,0.0,0.500000,0.454545,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
39,0.4375,0.0,0.333333,0.545455,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40,0.8750,0.0,0.500000,0.090909,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [ ]:
# Rename column

X_train_norm_df.rename(columns={'hour_of_day':'hour'}, inplace=True)

X_train_norm_df.head(2)

,hour,cash_type,Weekdaysort,Monthsort,coffee_name_Americano with Milk,coffee_name_Cappuccino,coffee_name_Cocoa,coffee_name_Cortado,coffee_name_Espresso,coffee_name_Hot Chocolate,coffee_name_Latte,Time_of_Day_Morning,Time_of_Day_Night
0,0.9375,0.0,1.000000,0.636364,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.5000,0.0,0.666667,0.272727,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0